export interface Employee {
  id: string
  name: string
  email: string
  department: string
  role: string
  level: string
  hire_date: string
  performance_score: number
  engagement_score: number
  attrition_risk_score: number
  salary: number
  market_benchmark: number
  compa_ratio: number
  last_review_date: string
  skills: string[]
}

export const employees: Employee[] = [
  { id: 'e1', name: 'Marcus Chen', email: 'marcus.chen@acme.com', department: 'Engineering', role: 'Senior Software Engineer', level: 'IC4', hire_date: '2021-03-15', performance_score: 92, engagement_score: 38, attrition_risk_score: 84, salary: 145000, market_benchmark: 172000, compa_ratio: 0.84, last_review_date: '2024-01-15', skills: ['React', 'Node.js', 'AWS', 'Python'] },
  { id: 'e2', name: 'Priya Sharma', email: 'priya.sharma@acme.com', department: 'Engineering', role: 'Staff Engineer', level: 'IC5', hire_date: '2020-07-01', performance_score: 95, engagement_score: 42, attrition_risk_score: 78, salary: 178000, market_benchmark: 210000, compa_ratio: 0.85, last_review_date: '2024-01-20', skills: ['Distributed Systems', 'Go', 'Kubernetes', 'Architecture'] },
  { id: 'e3', name: 'Jordan Williams', email: 'jordan.w@acme.com', department: 'Engineering', role: 'Software Engineer', level: 'IC3', hire_date: '2022-09-12', performance_score: 78, engagement_score: 55, attrition_risk_score: 72, salary: 118000, market_benchmark: 135000, compa_ratio: 0.87, last_review_date: '2024-02-01', skills: ['TypeScript', 'React', 'GraphQL'] },
  { id: 'e4', name: 'Aisha Thompson', email: 'aisha.t@acme.com', department: 'Engineering', role: 'Engineering Manager', level: 'M2', hire_date: '2019-11-05', performance_score: 88, engagement_score: 61, attrition_risk_score: 45, salary: 195000, market_benchmark: 205000, compa_ratio: 0.95, last_review_date: '2024-01-10', skills: ['Leadership', 'System Design', 'Python', 'Agile'] },
  { id: 'e5', name: 'Lucas Rodriguez', email: 'lucas.r@acme.com', department: 'Sales', role: 'Account Executive', level: 'IC3', hire_date: '2022-01-20', performance_score: 88, engagement_score: 72, attrition_risk_score: 38, salary: 95000, market_benchmark: 105000, compa_ratio: 0.90, last_review_date: '2024-02-15', skills: ['Salesforce', 'Negotiation', 'Enterprise Sales'] },
  { id: 'e6', name: 'Sofia Petrov', email: 'sofia.p@acme.com', department: 'Sales', role: 'Senior Account Executive', level: 'IC4', hire_date: '2021-06-14', performance_score: 91, engagement_score: 68, attrition_risk_score: 52, salary: 115000, market_benchmark: 130000, compa_ratio: 0.88, last_review_date: '2024-01-25', skills: ['Enterprise Sales', 'SaaS', 'Customer Success', 'Hubspot'] },
  { id: 'e7', name: 'Derek Okafor', email: 'derek.o@acme.com', department: 'Sales', role: 'Sales Manager', level: 'M1', hire_date: '2020-03-02', performance_score: 82, engagement_score: 75, attrition_risk_score: 28, salary: 155000, market_benchmark: 165000, compa_ratio: 0.94, last_review_date: '2024-02-10', skills: ['Team Management', 'Sales Strategy', 'Forecasting'] },
  { id: 'e8', name: 'Mei Nakamura', email: 'mei.n@acme.com', department: 'Product', role: 'Senior Product Manager', level: 'IC4', hire_date: '2021-08-30', performance_score: 90, engagement_score: 65, attrition_risk_score: 58, salary: 158000, market_benchmark: 178000, compa_ratio: 0.89, last_review_date: '2024-01-18', skills: ['Product Strategy', 'Data Analysis', 'SQL', 'Roadmapping'] },
  { id: 'e9', name: 'Thomas Brennan', email: 'thomas.b@acme.com', department: 'Product', role: 'Product Manager', level: 'IC3', hire_date: '2023-02-15', performance_score: 74, engagement_score: 70, attrition_risk_score: 32, salary: 128000, market_benchmark: 138000, compa_ratio: 0.93, last_review_date: '2024-02-20', skills: ['Agile', 'User Research', 'Analytics'] },
  { id: 'e10', name: 'Rachel Kim', email: 'rachel.k@acme.com', department: 'Marketing', role: 'Growth Marketing Lead', level: 'IC4', hire_date: '2021-04-12', performance_score: 85, engagement_score: 69, attrition_risk_score: 42, salary: 132000, market_benchmark: 145000, compa_ratio: 0.91, last_review_date: '2024-01-30', skills: ['Demand Gen', 'SEO', 'Paid Acquisition', 'Analytics'] },
  { id: 'e11', name: 'Oliver Bennett', email: 'oliver.b@acme.com', department: 'Marketing', role: 'Content Marketing Manager', level: 'IC3', hire_date: '2022-07-05', performance_score: 79, engagement_score: 63, attrition_risk_score: 35, salary: 108000, market_benchmark: 118000, compa_ratio: 0.92, last_review_date: '2024-02-08', skills: ['Content Strategy', 'SEO', 'Copywriting'] },
  { id: 'e12', name: 'Fatima Hassan', email: 'fatima.h@acme.com', department: 'Customer Success', role: 'Senior CSM', level: 'IC4', hire_date: '2020-10-20', performance_score: 89, engagement_score: 76, attrition_risk_score: 25, salary: 112000, market_benchmark: 120000, compa_ratio: 0.93, last_review_date: '2024-01-22', skills: ['Account Management', 'Onboarding', 'Salesforce', 'NPS'] },
  { id: 'e13', name: 'Carlos Mendez', email: 'carlos.m@acme.com', department: 'Customer Success', role: 'CSM', level: 'IC2', hire_date: '2023-06-01', performance_score: 72, engagement_score: 80, attrition_risk_score: 20, salary: 82000, market_benchmark: 88000, compa_ratio: 0.93, last_review_date: '2024-02-25', skills: ['Customer Success', 'Onboarding', 'Support'] },
  { id: 'e14', name: 'Nina Kowalski', email: 'nina.k@acme.com', department: 'Customer Success', role: 'VP Customer Success', level: 'M3', hire_date: '2019-05-15', performance_score: 91, engagement_score: 72, attrition_risk_score: 38, salary: 225000, market_benchmark: 240000, compa_ratio: 0.94, last_review_date: '2024-01-05', skills: ['Leadership', 'Churn Prevention', 'Revenue Growth', 'Strategy'] },
  { id: 'e15', name: 'James Park', email: 'james.p@acme.com', department: 'Finance', role: 'Financial Analyst', level: 'IC2', hire_date: '2022-11-01', performance_score: 80, engagement_score: 66, attrition_risk_score: 30, salary: 95000, market_benchmark: 102000, compa_ratio: 0.93, last_review_date: '2024-02-12', skills: ['Financial Modeling', 'Excel', 'SQL', 'Tableau'] },
  { id: 'e16', name: 'Sarah Mitchell', email: 'sarah.m@acme.com', department: 'Finance', role: 'Senior Financial Analyst', level: 'IC3', hire_date: '2021-02-10', performance_score: 86, engagement_score: 60, attrition_risk_score: 44, salary: 118000, market_benchmark: 132000, compa_ratio: 0.89, last_review_date: '2024-01-28', skills: ['FP&A', 'Budget Management', 'Financial Reporting', 'Netsuite'] },
  { id: 'e17', name: 'Ryan Torres', email: 'ryan.t@acme.com', department: 'Engineering', role: 'DevOps Engineer', level: 'IC3', hire_date: '2022-04-18', performance_score: 83, engagement_score: 48, attrition_risk_score: 65, salary: 130000, market_benchmark: 152000, compa_ratio: 0.86, last_review_date: '2024-02-05', skills: ['Kubernetes', 'AWS', 'Terraform', 'CI/CD'] },
  { id: 'e18', name: 'Amara Diallo', email: 'amara.d@acme.com', department: 'Engineering', role: 'Senior Backend Engineer', level: 'IC4', hire_date: '2020-09-14', performance_score: 87, engagement_score: 52, attrition_risk_score: 60, salary: 148000, market_benchmark: 168000, compa_ratio: 0.88, last_review_date: '2024-01-08', skills: ['Python', 'PostgreSQL', 'Redis', 'API Design'] },
  { id: 'e19', name: 'Ethan Brooks', email: 'ethan.b@acme.com', department: 'Product', role: 'Product Designer', level: 'IC3', hire_date: '2023-01-09', performance_score: 81, engagement_score: 77, attrition_risk_score: 22, salary: 115000, market_benchmark: 122000, compa_ratio: 0.94, last_review_date: '2024-02-18', skills: ['Figma', 'UX Research', 'Prototyping', 'Design Systems'] },
  { id: 'e20', name: 'Isabella Cruz', email: 'isabella.c@acme.com', department: 'Sales', role: 'SDR Manager', level: 'M1', hire_date: '2021-11-22', performance_score: 84, engagement_score: 71, attrition_risk_score: 33, salary: 125000, market_benchmark: 135000, compa_ratio: 0.93, last_review_date: '2024-02-02', skills: ['Outbound Sales', 'Team Leadership', 'Outreach', 'Coaching'] },
  { id: 'e21', name: 'Noah Gibson', email: 'noah.g@acme.com', department: 'Engineering', role: 'Frontend Engineer', level: 'IC2', hire_date: '2023-08-07', performance_score: 75, engagement_score: 58, attrition_risk_score: 48, salary: 102000, market_benchmark: 118000, compa_ratio: 0.86, last_review_date: '2024-02-22', skills: ['React', 'TypeScript', 'CSS', 'Testing'] },
  { id: 'e22', name: 'Zoe Lambert', email: 'zoe.l@acme.com', department: 'Marketing', role: 'Product Marketing Manager', level: 'IC4', hire_date: '2020-06-30', performance_score: 88, engagement_score: 67, attrition_risk_score: 40, salary: 138000, market_benchmark: 152000, compa_ratio: 0.91, last_review_date: '2024-01-14', skills: ['GTM Strategy', 'Competitive Analysis', 'Messaging', 'Analyst Relations'] },
  { id: 'e23', name: 'Liam Chen', email: 'liam.c@acme.com', department: 'Customer Success', role: 'Technical CSM', level: 'IC3', hire_date: '2022-03-14', performance_score: 85, engagement_score: 74, attrition_risk_score: 27, salary: 105000, market_benchmark: 112000, compa_ratio: 0.94, last_review_date: '2024-02-16', skills: ['Technical Onboarding', 'SQL', 'API', 'Customer Training'] },
  { id: 'e24', name: 'Hannah Foster', email: 'hannah.f@acme.com', department: 'Finance', role: 'Controller', level: 'M2', hire_date: '2019-08-05', performance_score: 90, engagement_score: 65, attrition_risk_score: 35, salary: 175000, market_benchmark: 188000, compa_ratio: 0.93, last_review_date: '2024-01-11', skills: ['GAAP', 'Financial Controls', 'Audit', 'NetSuite'] },
  { id: 'e25', name: 'Deon Washington', email: 'deon.w@acme.com', department: 'Engineering', role: 'Principal Engineer', level: 'IC5', hire_date: '2018-11-01', performance_score: 94, engagement_score: 44, attrition_risk_score: 76, salary: 195000, market_benchmark: 235000, compa_ratio: 0.83, last_review_date: '2023-12-20', skills: ['Architecture', 'Distributed Systems', 'Technical Strategy', 'Mentoring'] },
]
